### ISSUE TITLE
Check responsivenness and universalness of site

### ISSUE THREAD

**Issue by martinapugliese** [martinapugliese/martinapugliese.github.io#32]

**Comment by P403n1x87** [comment]
@martinapugliese Could you please elaborate on the title of the issue, please? Any particular area of the site that you feel would require more attention?

To speed up the build process, consider turning on the [incremental build](http://idratherbewriting.com/2015/11/04/jekyll-30-released-incremental-regeneration-rocks/) feature.

**Comment by martinapugliese** [comment]
@P403n1x87 👍

- [ ] check site is responsive in every device

Guess your suggestion is for the fact that it's slow to build

**Comment by P403n1x87** [comment]
The blog seems to have a responsive design already, so no work is required.
