### ISSUE TITLE
Put some stuff to follow the blog 

### ISSUE THREAD

**Issue by martinapugliese** [martinapugliese/martinapugliese.github.io#33]
like a follow button to some tool? Have to install the RSS reader, there is a button to it at the bottom of the blog. Or think of better solutions.

**Comment by P403n1x87** [comment]
An RSS feed seems to be already available at https://martinapugliese.github.io/feed.xml. Do you have something more specific in mind?

**Comment by martinapugliese** [comment]
Yea I have to set it up as gets a 404 for now.

**Comment by martinapugliese** [comment]
It's already there, closing
